import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import QueryProvider from '@/components/providers/QueryProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'E-Commerce',
  description: 'Generated by create next app',
};

/**
 * The root layout component for the app.
 * It wraps the `QueryProvider` from `@tanstack/react-query`
 * and sets up the font variables from Google Fonts.
 *
 * @param {React.ReactNode} children The children to render inside the layout.
 * @returns {JSX.Element} The root layout element.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider> {children} </QueryProvider>
      </body>
    </html>
  );
}
